// <auto-generated />
using LocalDBWebApiUsingEF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalDBWebApiUsingEF.Migrations
{
    [DbContext(typeof(DBManager))]
    [Migration("20230922022641_UserStructChange")]
    partial class UserStructChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("LocalDBWebApiUsingEF.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("Phone")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Bently",
                            Age = 20,
                            Email = "eamil1@gmail.com",
                            Name = "Sajib",
                            Password = "mypassword1",
                            Phone = -1111
                        },
                        new
                        {
                            Id = 2,
                            Address = "Victoria Park",
                            Age = 30,
                            Email = "eamil2@gmail.com",
                            Name = "Mistry",
                            Password = "mypassword1",
                            Phone = -2222
                        },
                        new
                        {
                            Id = 3,
                            Address = "Northbridge",
                            Age = 40,
                            Email = "eamil3@gmail.com",
                            Name = "Mike",
                            Password = "mypassword1",
                            Phone = -3333
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
