// <auto-generated />
using LocalDBWebApiUsingEF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalDBWebApiUsingEF.Migrations
{
    [DbContext(typeof(DBManager))]
    [Migration("20230922075549_Randome-Test")]
    partial class RandomeTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("LocalDBWebApiUsingEF.Models.BankAccount", b =>
                {
                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountHolderName")
                        .HasColumnType("TEXT");

                    b.Property<double>("Balance")
                        .HasColumnType("REAL");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountNumber");

                    b.HasIndex("UserId");

                    b.ToTable("BankAccounts");

                    b.HasData(
                        new
                        {
                            AccountNumber = 1,
                            AccountHolderName = "User1's Account",
                            Balance = 7961.459559686311,
                            UserId = 1
                        },
                        new
                        {
                            AccountNumber = 2,
                            AccountHolderName = "User2's Account",
                            Balance = 2981.7301179986621,
                            UserId = 2
                        },
                        new
                        {
                            AccountNumber = 3,
                            AccountHolderName = "User3's Account",
                            Balance = 3459.0267806906272,
                            UserId = 3
                        },
                        new
                        {
                            AccountNumber = 4,
                            AccountHolderName = "User4's Account",
                            Balance = 6465.3549225893494,
                            UserId = 4
                        },
                        new
                        {
                            AccountNumber = 5,
                            AccountHolderName = "User5's Account",
                            Balance = 9601.417471628085,
                            UserId = 5
                        },
                        new
                        {
                            AccountNumber = 6,
                            AccountHolderName = "User6's Account",
                            Balance = 2878.910772457496,
                            UserId = 6
                        },
                        new
                        {
                            AccountNumber = 7,
                            AccountHolderName = "User7's Account",
                            Balance = 4494.3094863356901,
                            UserId = 7
                        },
                        new
                        {
                            AccountNumber = 8,
                            AccountHolderName = "User8's Account",
                            Balance = 316.54979178725171,
                            UserId = 8
                        },
                        new
                        {
                            AccountNumber = 9,
                            AccountHolderName = "User9's Account",
                            Balance = 7003.8382905224771,
                            UserId = 9
                        },
                        new
                        {
                            AccountNumber = 10,
                            AccountHolderName = "User10's Account",
                            Balance = 1804.2373217178408,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("LocalDBWebApiUsingEF.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Picture")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Address 1",
                            Age = 51,
                            Email = "user1@mail.com",
                            Name = "User1",
                            Password = "password1",
                            Phone = "123-456-1",
                            Picture = "/images/man2.jpeg"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Address 2",
                            Age = 41,
                            Email = "user2@mail.com",
                            Name = "User2",
                            Password = "password2",
                            Phone = "123-456-2",
                            Picture = "/images/man2.jpeg"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Address 3",
                            Age = 59,
                            Email = "user3@mail.com",
                            Name = "User3",
                            Password = "password3",
                            Phone = "123-456-3",
                            Picture = "/images/women2.jpeg"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Address 4",
                            Age = 31,
                            Email = "user4@mail.com",
                            Name = "User4",
                            Password = "password4",
                            Phone = "123-456-4",
                            Picture = "/images/man1.jpeg"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Address 5",
                            Age = 37,
                            Email = "user5@mail.com",
                            Name = "User5",
                            Password = "password5",
                            Phone = "123-456-5",
                            Picture = "/images/women2.jpeg"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Address 6",
                            Age = 25,
                            Email = "user6@mail.com",
                            Name = "User6",
                            Password = "password6",
                            Phone = "123-456-6",
                            Picture = "/images/man1.jpeg"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Address 7",
                            Age = 44,
                            Email = "user7@mail.com",
                            Name = "User7",
                            Password = "password7",
                            Phone = "123-456-7",
                            Picture = "/images/women2.jpeg"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Address 8",
                            Age = 34,
                            Email = "user8@mail.com",
                            Name = "User8",
                            Password = "password8",
                            Phone = "123-456-8",
                            Picture = "/images/women1.jpeg"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Address 9",
                            Age = 33,
                            Email = "user9@mail.com",
                            Name = "User9",
                            Password = "password9",
                            Phone = "123-456-9",
                            Picture = "/images/man2.jpeg"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Address 10",
                            Age = 59,
                            Email = "user10@mail.com",
                            Name = "User10",
                            Password = "password10",
                            Phone = "123-456-10",
                            Picture = "/images/women1.jpeg"
                        });
                });

            modelBuilder.Entity("LocalDBWebApiUsingEF.Models.BankAccount", b =>
                {
                    b.HasOne("LocalDBWebApiUsingEF.Models.User", "User")
                        .WithMany("BankAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LocalDBWebApiUsingEF.Models.User", b =>
                {
                    b.Navigation("BankAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
